### ISSUE TITLE
Systax Error

### ISSUE THREAD

**Issue by anandharaj-dotworld** [bongtrop/hbctool#13]
```
hbctool
Traceback (most recent call last):
  File "/usr/local/bin/hbctool", line 11, in <module>
    load_entry_point('hbctool==0.1.5', 'console_scripts', 'hbctool')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/hbctool-0.1.5-py2.7.egg/hbctool/__init__.py", line 31
    print(f"[*] Disassemble '{hbcfile}' to '{hasmpath}' path")
                                                            ^
SyntaxError: invalid syntax
```

**Comment by Vendicated** [comment]
Use python3
