### ISSUE TITLE
HBC Version (84) Error

### ISSUE THREAD

**Issue by dhaneshnarmatha** [bongtrop/hbctool#21]
- I recently tried to decompile the index.android.bundle file with `hbctool`
- But when tried I faced with this issue

```bash
# error
(hbctool) dnoscp@arupadaiveedu:~/Desktop/data/PATCH2$ hbctool disasm apktool/assets/index.android.bundle decompiled
[*] Disassemble 'apktool/assets/index.android.bundle' to 'decompiled' path
Traceback (most recent call last):
  File "/opt/tools/hbctool/bin/hbctool", line 8, in <module>
    sys.exit(main())
  File "/opt/tools/hbctool/lib/python3.10/site-packages/hbctool/__init__.py", line 61, in main
    disasm(args['<HBC_FILE>'], args['<HASM_PATH>'])
  File "/opt/tools/hbctool/lib/python3.10/site-packages/hbctool/__init__.py", line 33, in disasm
    hbco = hbc.load(f)
  File "/opt/tools/hbctool/lib/python3.10/site-packages/hbctool/hbc/__init__.py", line 29, in load
    assert version in HBC, f"The HBC version ({version}) is not supported."
AssertionError: The HBC version (84) is not supported.
```

- The information of the file
 
```bash
# file info
(hbctool) dnoscp@arupadaiveedu:~/Desktop/data/PATCH2$ file apktool/assets/index.android.bundle 
apktool/assets/index.android.bundle: Hermes JavaScript bytecode, version 84
```

- Someone please help to solve this issue.

**Comment by AlaaEdAouimeur** [comment]
+1

**Comment by dhaneshnarmatha** [comment]
**CLOSING THE ISSUE** : Got the solution. from #12 

@AlaaEdAouimeur, this worked for me. give it a try


```bash
# I did everything in a virtualenvironment
git clone https://github.com/niosega/hbctool.git
cd hbctool
git checkout origin/draft/hbc-v84
pip install -r requirements.txt
poetry install
hbctool disasm assets/index.android.bundle/ output
```
