### ISSUE TITLE
FYI : updates version 84,85,89 and test corrections

### ISSUE THREAD

**Issue by anantshri** [bongtrop/hbctool#23]
Hi @bongtrop Thanks for the nice tool.

I have been working on updating few things here : https://github.com/cyfinoid/hbctool

I see 84,85 support got merged recently hence cant open a clear pull request. Following changes are available in my branch if you want to cherrypick

1. Version support added 84 (via niosega), 85,89,83
2. Test cases are now running some fixing was needed
3. Added a readme on how to add new versions.

Feel free to pick and choose

**Comment by bongtrop** [comment]
Awesome contribution. I'm working on it. I will merge it soon.

**Comment by bongtrop** [comment]
I'm working on it. Please find the merge request here #24.

**Comment by bongtrop** [comment]
I'm working on it at #25.

**Comment by amirhoseinsb** [comment]
Not Working script for me 
--------------------------------------------------------------------------------------------
[*] Disassemble 'index.android.bundle' to 'test_hasm' path
Traceback (most recent call last):
  File "/home/amir/.local/bin/hbctool", line 8, in <module>
    sys.exit(main())
  File "/home/amir/.local/lib/python3.10/site-packages/hbctool/__init__.py", line 61, in main
    disasm(args['<HBC_FILE>'], args['<HASM_PATH>'])
  File "/home/amir/.local/lib/python3.10/site-packages/hbctool/__init__.py", line 33, in disasm
    hbco = hbc.load(f)
  File "/home/amir/.local/lib/python3.10/site-packages/hbctool/hbc/__init__.py", line 29, in load
    assert version in HBC, f"The HBC version ({version}) is not supported."
AssertionError: The HBC version (85) is not supported.
