### ISSUE TITLE
i am getting the following error on the 84 version

### ISSUE THREAD

**Issue by Philmon43** [bongtrop/hbctool#27]
[*] Disassemble 'index.android.bundle' to 'hbctool' path
Traceback (most recent call last):
  File "/usr/local/bin/hbctool", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/hbctool/__init__.py", line 61, in main
    disasm(args['<HBC_FILE>'], args['<HASM_PATH>'])
  File "/usr/local/lib/python3.9/site-packages/hbctool/__init__.py", line 33, in disasm
    hbco = hbc.load(f)
  File "/usr/local/lib/python3.9/site-packages/hbctool/hbc/__init__.py", line 29, in load
    assert version in HBC, f"The HBC version ({version}) is not supported."
AssertionError: The HBC version (84) is not supported.

**Comment by Philmon43** [comment]
fixed!  i had old version of hbctool :)
