### ISSUE TITLE
The HBC version (90) is not supported.

### ISSUE THREAD

**Issue by ddguru777** [bongtrop/hbctool#39]
I tried to decompile hermes bytecode and failed.
` hbctool disasm assets/index.android.bundle ../hermes_out           
[*] Disassemble 'assets/index.android.bundle' to '../hermes_out' path
Traceback (most recent call last):
  File "/usr/local/bin/hbctool", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hbctool/__init__.py", line 61, in main
    disasm(args['<HBC_FILE>'], args['<HASM_PATH>'])
  File "/usr/local/lib/python3.11/site-packages/hbctool/__init__.py", line 33, in disasm
    hbco = hbc.load(f)
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hbctool/hbc/__init__.py", line 29, in load
    assert version in HBC, f"The HBC version ({version}) is not supported."
           ^^^^^^^^^^^^^^
AssertionError: The HBC version (90) is not supported.`

**Comment by powereureka** [comment]
i have a version with support of hbc v90

**Comment by chanphiromsok** [comment]
> i have a version with support of hbc v90

do you have 94 ?

**Comment by powereureka** [comment]
yes i have it

**Comment by chanphiromsok** [comment]
> yes i have it

I found solution thx you

**Comment by afroman443** [comment]
> yes i have it

Hi, are you able to send me a link with version 90 support? I'd really appreciate it, thank you

**Comment by powereureka** [comment]
email me on comisazha@gmail.com
