### ISSUE TITLE
AssertionError: The HBC version (85) is not supported.

### ISSUE THREAD

**Issue by 0xS4D** [bongtrop/hbctool#41]
[*] Disassemble '.\index.android.bundle' to '.\output\' path
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\hbctool.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\hbctool\__init__.py", line 61, in main
    disasm(args['<HBC_FILE>'], args['<HASM_PATH>'])
  File "C:\Python311\Lib\site-packages\hbctool\__init__.py", line 33, in disasm
    hbco = hbc.load(f)
           ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\hbctool\hbc\__init__.py", line 29, in load
    assert version in HBC, f"The HBC version ({version}) is not supported."
           ^^^^^^^^^^^^^^
AssertionError: The HBC version (85) is not supported.

**Comment by jamesmacwhite** [comment]
Use a fork which has the bytecode version implemented e.g. https://github.com/gilcu3/hbctool
